apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cassandra
    cluster: medusa-dev
  name: cassandra
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cassandra
      cluster: medusa-dev
  serviceName: cassandra
  template:
    metadata:
      labels:
        app: cassandra
        cluster: medusa-dev
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cassandra
                - key: cluster
                  operator: In
                  values:
                  - medusa-dev
              topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        #- name: DEBUG_SLEEP
        #  value: "180"
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.medusa.svc.cluster.local,cassandra-1.cassandra.medusa.svc.cluster.local
        - name: MAX_HEAP_SIZE
          value: 512M
        - name: HEAP_NEWSIZE
          value: 512M
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: SimpleSnitch
        - name: CASSANDRA_CLUSTER_NAME
          value: medusa-dev
        - name: CASSANDRA_DC
          value: DC1
        - name: CASSANDRA_RACK
          value: RAC1
        - name: CASSANDRA_START_RPC
          value: "false"
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: jsanda/cassandra:3.11.6-dev
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nodetool status
          failureThreshold: 3
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: cassandra
        ports:
        - containerPort: 7000
          name: intra
          protocol: TCP
        - containerPort: 7001
          name: tls
          protocol: TCP
        - containerPort: 7199
          name: jmx
          protocol: TCP
        - containerPort: 9042
          name: cql
          protocol: TCP
        - containerPort: 9160
          name: thrift
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nodetool status | grep -E "^UN\s+${POD_IP}"
          failureThreshold: 3
          initialDelaySeconds: 90
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: data
        - name: cassandra-config
          mountPath: /etc/cassandra
      - name: medusa
        image: jsanda/medusa:grpc-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        # I temporarily introduced a flag in the medusa gRPC service to put it to sleep
        # to make it easier to debug issues with the medusa image.
        #env:
        #- name: DEBUG_SLEEP
        #  value: "300"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 10
        volumeMounts:
          - name: medusa-gcp-key
            mountPath: /etc/medusa/medusa_gcp_key.json
            subPath: medusa_gcp_key.json
          - name: medusa-config
            mountPath: /etc/medusa/medusa.ini
            subPath: medusa.ini
          - name: cassandra-config
            mountPath: /etc/cassandra
          - mountPath: /var/lib/cassandra
            name: data
      volumes:
        - name: cassandra-config
          emptyDir: {}
        - name: medusa-gcp-key
          configMap: 
            name: medusa-gcp-key
            items:
            - key: medusa_gcp_key.json
              path: medusa_gcp_key.json
        - name: medusa-config
          configMap:
            name: medusa-config
            items:
            - key: medusa.ini
              path: medusa.ini
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: cassandra
        cluster: medusa-dev
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
